### ISSUE TITLE
Worker HTTP request error when set the request body

### ISSUE THREAD

**Issue by kevi-sun** [cloudflare/workers-rs#132]
I need to generate a HTTP request inside the Cloudflare Worker which might include customised headers and body, and when I set the body, it always get the following error: 
```text
"Failed to init request https://google.com with detail invalid URL or options for Request"
```

I have above error in two cases:
- If I set the "init.with_body", I always get the above error, with or without set the "Content-Length"
- If I remove the "init.with_body", also without "Content-Length" header, then it is fine
- If I have "Content-Length" set, but without body, it also report above error.

so it looks like it might related with the Content-Lenght has to consistent with body, but I tried both "3" and "4" for body "foo", both failed.

Here is the run environment:
- OS: ubuntu 20.04 (running as docker)
- Rust: rustc 1.57.0 (f1edd0429 2021-11-29)
- crate worker: 0.0.8
- running with miniflare

```rust
pub async fn get_url() -> Result<String, String> {
    let mut headers = worker::Headers::new();
    headers.set("User-Agent", "PostmanRuntime/7.29.0").unwrap();
    headers.set("Accept-Encoding", "gzip, deflate, br").unwrap();
    headers.set("Content-Type", "text/plain").unwrap();
    headers.set("extra-header", "foobar").unwrap();
    // headers.set("Content-Length", "3").unwrap();

    let body = "foo";

    let mut init = RequestInit::new();
    init.with_method(worker::Method::Get);
    init.with_headers(headers);
    init.with_body(Some(JsValue::from_str(body)));

    let url = "https://google.com";

    let request = Request::new_with_init(url, &init)
        .map_err(|err| format!("Failed to init request {} with detail {}", url, err))?;

    let mut response = Fetch::Request(request)
        .send()
        .await
        .map_err(|err| format!("Failed to get the response from {} with detail {}", url, err))?;

    if response.status_code() != 200 {
        return Err(format!("Response StatusCode: {}", response.status_code()));
    }

    let response_body = response.text().await.unwrap();
    Ok(response_body)
}
```

**Comment by zebp** [comment]
I'll look into this today or tomorrow and report back!

**Comment by zebp** [comment]
I looked into this and it seems that this isn't an issue with workers-rs specifically but limitations with workers (and miniflare) itself. If you look at [this gist](https://gist.github.com/zebp/407944e6ba5df7fefd351e63a9b6188b) you'll see that a normal JavaScript worker fails in the exact same ways as you described for your Rust worker.

Because this isn't a problem with workers-rs specifically you are best off using the feedback button on our [fetch documentation](https://developers.cloudflare.com/workers/runtime-apis/fetch) or asking in the [Cloudflare Developer Discord](https://discord.com/invite/cloudflaredev).

**Comment by kevi-sun** [comment]
just for completion, with further test, I found that Method Post do support having body, only some of the Method (e.g. Get as this example) couldn't have body.
