### ISSUE TITLE
[BUG] wrangler publish generates empty Worker

### ISSUE THREAD

**Issue by SebastiaanYN** [cloudflare/workers-rs#276]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of `workers-rs` are you using?

0.0.11

### Describe the bug

When publishing a Worker the WASM binary is not included in the output, resulting in `Cannot read properties of undefined (reading 'fetch')`.

This occurs on both MacOS and WSL2 as well as with later versions/commits of workers-rs.

The WASM binary does get created:
```sh
$ ls -lah build/worker 
total 960
drwxr-xr-x  4 sebastiaan  staff   128B Feb  6 16:59 .
drwxr-xr-x  7 sebastiaan  staff   224B Feb  6 16:59 ..
-rw-r--r--  1 sebastiaan  staff   453K Feb  6 16:59 index.wasm
-rw-r--r--  1 sebastiaan  staff    21K Feb  6 16:59 shim.mjs
```

but not included in the output:
```sh
$ npx wrangler publish --dry-run --name foo | grep "Total Upload"
Total Upload: 21.23 KiB / gzip: 4.58 KiB
```

Versions:
```sh
$ cargo tree | grep worker
todo-worker v0.0.0
└── worker v0.0.11
    ├── worker-kv v0.5.1
    ├── worker-macros v0.0.6 (proc-macro)
    │   └── worker-sys v0.0.6
    └── worker-sys v0.0.6 (*)

$ rustup --version
rustup 1.25.1 (bb60b1e89 2022-07-12)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.66.0 (69f9c33d7 2022-12-12)`

$ node --version                              
v16.16.0
```

### Steps To Reproduce

1. `npm init cloudflare project_name worker-rust`
2. `npx wrangler publish --name foo` (`--dry-run` optionally)
3. Check upload size: `Total Upload: 21.23 KiB / gzip: 4.58 KiB`
4. Accessing the Worker results in `Cannot read properties of undefined (reading 'fetch')`

**Comment by Alex1607** [comment]
I am having the same issue with my project on Windows 10.
I did some research and found out this issue doesn't exist when using the worker version `0.0.9`.
Since I already wrote something about this on the Discord, I just copied and pasted what I wrote there:
> Found the issue, it wasn't the command nor the template. The issue is that worker = "0.0.11" doesn't work in the templates. I just cloned the old rust template (https://github.com/cloudflare/rustwasm-worker-template) and it worked. So I tested out what changes there are to the new template (https://github.com/cloudflare/templates). 
Here is the important line: https://github.com/cloudflare/templates/blob/main/worker-rust/Cargo.toml#L14 In the old templates its 0.0.9 which works. 
Now its just the question why did it break with the 0.0.10? I am using Windows 10 but I could also check it out on WSL to see how it works under linux.

**Comment by CathalMullan** [comment]
Instead of using `worker-build` directly, I rewrote it as a bash script, and ran each command individually to try and figure out the problem.

In `worker-build`, there is a function called `use_glue_import` which alters the JS generated by `wasm-pack`.

```rust
// Replaces the wasm import with an import that instantiates the WASM modules itself.
fn use_glue_import() -> Result<()> {
    let bindgen_glue_path = worker_path(format!("{OUT_NAME}_bg.js"));
    let old_bindgen_glue = read_file_to_string(&bindgen_glue_path)?;
    let old_import = format!("import * as wasm from './{OUT_NAME}_bg.wasm'");
    let fixed_bindgen_glue = old_bindgen_glue.replace(&old_import, "import wasm from './glue.js'");
    write_string_to_file(bindgen_glue_path, fixed_bindgen_glue)?;
    Ok(())
}
```

It expects an import statement like `import * as wasm from './{OUT_NAME}_bg.wasm'` in `{OUT_NAME}_bg.js`, and replaces it with `import wasm from './glue.js'`.

With `worker = "0.0.9"`, I can see the expected import statement in the `wasm-pack` generated JS file.

```js
import * as wasm from "./index_bg.wasm";
```

But with `worker = "0.0.10"`, that import statement is gone, and seemingly replaced with this:

```js
let wasm;
export function __wbg_set_wasm(val) {
  wasm = val;
}
```

As for why the import statement is no longer there - no clue! Probably a dependency update somewhere?

**Comment by Alex1607** [comment]
I did some research on GitHub, and it seems like this: `__wbg_set_wasm` function was added to wasm-bindgen on the 17th November 2022: https://github.com/rustwasm/wasm-bindgen/commit/721c86c3467750bf2a46bf85941e6c211ae9e87a and this repo just happens to be one of the dependencies for workers-rs and more: https://github.com/rustwasm/wasm-bindgen/network/dependents?owner=cloudflare&dependent_type=REPOSITORY&owner=cloudflare
So, I guess it's probably from somewhere around there. My best guess would be that this method should be called by \*something\* on cloudflares end / from the workers, but I might just be entirely wrong, since I don't work with JS at all.

**Comment by CathalMullan** [comment]
Opened a PR with the simple/naive solution, changing the replacement format to match the newer `wasm-bindgen` import.

**Comment by CathalMullan** [comment]
Until that PR gets merged, a short-term solution for the `TypeError: Cannot read properties of undefined (reading 'fetch')` issue is to change the build command in `wrangler.toml` to use my forked version of `worker-build` 

```toml
[build]
command = "cargo install --git https://github.com/CathalMullan/workers-rs worker-build && worker-build --release"
```

**Comment by JorritSalverda** [comment]
Any chance `worker-build` version `0.0.9` gets released soon, so we no longer have to use `https://github.com/CathalMullan/workers-rs` or `workers` version `0.0.9`?

**Comment by zebp** [comment]
> Any chance `worker-build` version `0.0.9` gets released soon, so we no longer have to use `https://github.com/CathalMullan/workers-rs` or `worker` version `0.0.9`?

I plan on cutting a new workers-rs release tomorrow or Monday, depending on how some testing goes.

**Comment by JorritSalverda** [comment]
Awesome, looking forward to it! 😄

**Comment by imaxisXD** [comment]
Still happening for me using the doc https://developers.cloudflare.com/browser-rendering/get-started/screenshots/
but the fetch error is still present
