### ISSUE TITLE
[BUG] js-sys 0.3.70 breaking change

### ISSUE THREAD

**Issue by gmemstr** [cloudflare/workers-rs#617]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of `workers-rs` are you using?

0.3.3

### What version of `wrangler` are you using?

3.71.0

### Describe the bug

It appears that the js-sys crate released a breaking change.

```
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   /home/user/projects/ap-gateway/ingress/Cargo.toml
workspace: /home/user/projects/ap-gateway/Cargo.toml
    Checking worker v0.3.3
error[E0599]: no method named `unwrap` found for struct `js_sys::Iterator` in the current scope
  --> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/worker-0.3.3/src/headers.rs:83:14
   |
80 | /         self.0
81 | |             .keys()
82 | |             // Header.keys() doesn't error: https://developer.mozilla.org/en-US/docs/Web/API/Headers/keys
83 | |             .unwrap()
   | |             -^^^^^^ method not found in `Iterator`
   | |_____________|
   |

error[E0599]: no method named `unwrap` found for struct `js_sys::Iterator` in the current scope
  --> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/worker-0.3.3/src/headers.rs:95:14
   |
92 | / ...   self.0
93 | | ...       .values()
94 | | ...       // Header.values() doesn't error: https://developer.mozilla.org/en-US/docs/Web/API/Headers/va...
95 | | ...       .unwrap()
   | |           -^^^^^^ method not found in `Iterator`
   | |___________|
   |

error[E0599]: no method named `unwrap` found for struct `js_sys::Iterator` in the current scope
  --> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/worker-0.3.3/src/headers.rs:69:14
   |
66 | / ...   self.0
67 | | ...       .entries()
68 | | ...       // Header.entries() doesn't error: https://developer.mozilla.org/en-US/docs/Web/API/Headers/e...
69 | | ...       .unwrap()
   | |           -^^^^^^ method not found in `Iterator`
   | |___________|
   |

error[E0277]: the `?` operator can only be applied to values that implement `Try`
  --> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/worker-0.3.3/src/http/header.rs:11:16
   |
11 |     for res in from_headers.entries()?.into_iter() {
   |                ^^^^^^^^^^^^^^^^^^^^^^^ the `?` operator cannot be applied to type `js_sys::Iterator`
   |
   = help: the trait `Try` is not implemented for `js_sys::Iterator`

Some errors have detailed explanations: E0277, E0599.
For more information about an error, try `rustc --explain E0277`.
error: could not compile `worker` (lib) due to 4 previous errors
```

Currently trying to track down which version specifically contained this change.

### Steps To Reproduce

1. Create a new workers-rs project
2. Create a basic handler with the http feature
3. Run `cargo check` or `npx wrangler dev`

**Comment by gmemstr** [comment]
A workaround: Add to your `Cargo.toml`:

```toml
[dependencies]
wasm-bindgen = "=0.2.92"
```

**Comment by fornwall** [comment]
Another temporary workaround is using the branch from #619 temporarily:

```toml
worker = { git = "https://github.com/fornwall/workers-rs", branch = "js-sys-0.3.70" }
```

**Comment by omarabid** [comment]
@kflansburg Can you point out the change in js-sys that caused this? I looked into the keys function (https://github.com/rustwasm/wasm-bindgen/blame/ddceac747876d67fe52dafc90964f95741ae467d/crates/js-sys/src/lib.rs#L2194) and it's the same since 6 years ago.

**Comment by kflansburg** [comment]
> @kflansburg Can you point out the change in js-sys that caused this? I looked into the keys function (https://github.com/rustwasm/wasm-bindgen/blame/ddceac747876d67fe52dafc90964f95741ae467d/crates/js-sys/src/lib.rs#L2194) and it's the same since 6 years ago.

I attempted to find it this morning, and was not able to identify the change. I haven't seen anyone else open an issue, so I appreciate you doing so. We will see what they say.

**Comment by andrewdavidmackenzie** [comment]
When I try the wasm-bindgen dependency version workaround I run into version incompatibility of it, as I also use leptos in my project.

When I try the other workaorund mentioned above (`worker = { git = "https://github.com/fornwall/workers-rs", branch = "js-sys-0.3.70" }`) I get this output during build:
```
 ⛅️ wrangler 3.57.0 (update available 3.72.0)
-------------------------------------------------------
Running custom build: cargo install -q worker-build && worker-build --release
[INFO]: 🎯  Checking for the Wasm target...
[INFO]: 🌀  Compiling to Wasm...
error: invalid character `{` in package name: `{{project-name}}`, the first character must be a Unicode XID start character (most letters or `_`)
 --> ../../../.cargo/git/checkouts/workers-rs-e108b3103026828f/61d8c77/templates/hello-world-http/Cargo.toml:2:8
  |
2 | name = "{{project-name}}"
  |        ^^^^^^^^^^^^^^^^^^
  |
error: invalid character `{` in package name: `{{project-name}}`, the first character must be a Unicode XID start character (most letters or `_`)
 --> ../../../.cargo/git/checkouts/workers-rs-e108b3103026828f/61d8c77/templates/hello-world/Cargo.toml:2:8
  |
2 | name = "{{project-name}}"
  |        ^^^^^^^^^^^^^^^^^^
  |
error: invalid character `{` in package name: `{{project-name}}`, the first character must be a Unicode XID start character (most letters or `_`)
 --> ../../../.cargo/git/checkouts/workers-rs-e108b3103026828f/61d8c77/templates/axum/Cargo.toml:2:8
  |
2 | name = "{{project-name}}"
  |        ^^^^^^^^^^^^^^^^^^
```

So, I'm interested in a release with the fix to this...

**Comment by avsaase** [comment]
We fixed this by pinning `js-sys` instead of `wasm-bindgen`:
```toml
js-sys = "=0.3.69"
```
Make sure to run `cargo clean` to be sure the correct version is used.

**Comment by avsaase** [comment]
If you can I recommend using workspace dependencies to make sure the same version is used in all workspace members.

**Comment by omarabid** [comment]
> > @kflansburg Can you point out the change in js-sys that caused this? I looked into the keys function (https://github.com/rustwasm/wasm-bindgen/blame/ddceac747876d67fe52dafc90964f95741ae467d/crates/js-sys/src/lib.rs#L2194) and it's the same since 6 years ago.
> 
> I attempted to find it this morning, and was not able to identify the change. I haven't seen anyone else open an issue, so I appreciate you doing so. We will see what they say.

Investigated today a bit further. This might, potentially, be a problem with workers-rs rather than wasm-bindgen.

So here is the situation.

If js-sys 0.3.69 is selected, these functions are called: https://github.com/cloudflare/workers-rs/blob/6a5bfc1c8d84e32f84518832920e1c9d238e7876/worker-sys/src/ext/headers.rs#L23

These functions return a Result which has the Iterator and can support unwrapping. More importantly, these functions are provided by workers-rs crate (worker-sys)

If js-sys 0.3.70 is selected, these functions are called: https://github.com/rustwasm/wasm-bindgen/blob/240fbd247342036da8432dc62df48db24a46ff1d/crates/web-sys/src/features/gen_Headers.rs#L58 They were added recently and they are, I suppose, the "glue" functions for the Headers object.

So, my essential understanding, is that these functions were not provided by wasm-bindgen to begin with and the author of worker-sys made an implementation. But now that wasm-bindgen is providing an implementation, it's getting picked up instead. I probably don't understand how this extern C gluing work exactly, since I'd expect an error about conflict implementations?

Either way, I think the correct approach now is to remove the worker-sys implementations and adjust any code that might break.

**Comment by kflansburg** [comment]
Ah, very interesting, awesome find! Let me give that a shot.

**Comment by avsaase** [comment]
Nice work on finding the cause and implementing the fix!

I think a crate adding new methods is not "officially" a breaking change, even though they may conflict with extension traits in library consumers. It's an unfortunate grey area because it does break the consumer's code but requiring a major bump would be complete unworkable for library authors. I just wanted to point this out to make it clear that the `js-sys` authors are not to blame for breaking semver, at least not according to the definition commonly used in the Rust ecosystem.

**Comment by kflansburg** [comment]
I agree, it is a grey area. We deal with similar issues when implementing new APIs in Workers JavaScript runtime.

**Comment by omarabid** [comment]
@avsaase It's not a breaking change in wasm-bindgen. The initial confusion came from the fact that the build broke just by updating a patch version in js-sys. So kinda the finger was pointed to that direction.

@kflansburg Thanks for the quick release ;)
