### ISSUE TITLE
Responses being mangled

### ISSUE THREAD

**Issue by thomasfoster96** [cloudflare/workers-rs#64]
I’m experimenting with using the `async-graphql` crate inside a worker. When I use `wee_alloc` as the global allocator, the first few bytes of each response from the worker are being consistently ‘mangled’ for some reason. Here is a repository with a minimal worker which replicates the issue: https://github.com/thomasfoster96/wealloc-issue and here is the worker in action: https://wealloc-issue.thomasfoster.workers.dev/.

Here I what I would expect my worker to produce:
```json
{"data":null,"errors":[{"message":"Bad Request"}]}
```
Instead, this is what I get:
```json
��ta":null,"errors":[{"message":"Bad Request"}]}
```

The bytes are mangled the same way on every request. Calling `serde_json::to_string` on the GraphQL request and then logging it with `console_log!` produces the correct output — this is only happening when I use `Response::from_json` or similar methods.

Creating a response body in other ways produces similar results. For example, using `serde_json::to_string` produces the correct output but using `Response::from_html` then mangles it, as does using `serde_json::to_vec` and then `Response::from_bytes`.

(Apologies if any of this is unclear, I’m very much a beginner with Rust and Cloudflare Workers)

**Comment by dbw9580** [comment]
I have also encountered this issue, although in my case not always reproducible. Not sure if this is related: https://rustwasm.github.io/docs/wasm-bindgen/reference/types/str.html#utf-16-vs-utf-8

**Comment by nilslice** [comment]
I'd avoid using `wee_alloc` for as long as you can. 

Does your bundle size _require_ you to use `wee_alloc` ? If not, I would solve this issue by dropping it altogether. We aren't likely going to be able to prioritize looking into this at this time. Maybe the rustwasm working group can take a look? 

I will most likely remove it from the optional deps in the template before the next release. Sorry if it has come across as a recommendation, but it's mostly a last resort for pruning every byte possible from your Worker bundle upload.

**Comment by thomasfoster96** [comment]
@dbw9580 I did initially think it could be a text encoding issue, but the issue persisted even when using `Response::from_bytes` so I don’t think it’s text-related. Not to mention that it’s only affecting the first 2–4 bytes of the response body, when I’d expect text encoding problems to affect the entirety of it.

**Comment by thomasfoster96** [comment]
@nilslice I don’t *need* to use `wee_alloc`, but the worker size is getting close to the Workers limit so I was trying it out to see if there were any noticeable savings. The worker is around 1.3MB uncompressed, but wrangler is uploading it successfully so it’s clearly below that after whatever compression (I think `async-graphql` uses a lot of easily compressible static strings). Removing `wee_alloc` as an optional dependency would be great for people like me who naively thought it was a piece of low-hanging fruit as far as optimisations go — `lto = true` and `opt-level = "z"` work perfectly fine and give much bigger savings, and I doubt there would be any workers which would be big enough for those two settings to blow out compile times.

I’ll create an issue for [rustwasm/wee_alloc](https://github.com/rustwasm/wee_alloc) and follow-up there — I’d created the issue here because everything else in the worker is working fine with `wee_alloc`, the problem seems to only be occurring within `Response`. This is a wild guess, but given it’s the first 4 bytes of the body which are the problem, something might trying to interpret the first four bytes of the response body as a `usize`, i.e. as a pointer or a length.

**Comment by nilslice** [comment]
That sounds good! And it's totally reasonable to expect it to work. I've seen it work in the past with different projects, but there a other layers at play here between the Worker and actually serving the final response back to the user which will take a while to get on anyone's roadmap.

**Comment by thomasfoster96** [comment]
@nilslice in [the worker I gave as an example](https://github.com/thomasfoster96/wealloc-issue) works as expected if the two lines which set `wee_alloc` as the global allocator are removed.

Since reporting this issue however, I swapped `async-graphql` with `juniper` in my worker (which saves ~500kb), but now have a similar issue with the same mangling of the first 2-4 bytes of responses, but also the final one or two bytes being truncated. This is occurring *without* `wee_alloc`, but also only within responses with a 4XX status code — if the worker responds with a 200 OK, everything’s fine. This is also causing Safari to try and download the worker body as a text file if the response is mangled.

**Comment by rkusa** [comment]
I had the same issue recently, but completely outside of `wasm-bindgen`, Cloudflare and wrangler. I was compiling `mozjpeg-sys` to `wasm-wasi` (wasn't using `wasm-bindgen`). When I encoded an image to JPEG, the first bytes (I think it were also four byte) where replaced with `0`, too (resulting in an invalid JPEG file). I fixed it by removing `we_alloc`. The size difference without `we_alloc` was only `1kb` or so, so I didn't even care. That being said, since I saw the same in a completely different use-case, it sounds to me like it might be an issue with `we_alloc`?

**Comment by cjpatton** [comment]
I'm experiencing the response garbling issue when running miniflare to mock a durable object. Two things I noticed:
1. Responses only get garbled if I make a request to the DO
2. Responses only get garbled *sometimes*. It seems to work just fine 25% of the time.

**Comment by nilslice** [comment]
@cjpatton - interesting! can you update once more when you've got this published?

**Comment by ByteAlex** [comment]
I've encountered the same issue just today.
The first *few* bytes seem to be odd *sometimes*. When a worker restarts (due to a new script being uploaded for example), it mostly runs fine for a while, but will start erroring soon.
It's not always a fixed amount of bytes, it seems to be depending on the size of the object.
For example, I have one response which is always similar in size, there's always the first 8 bytes being mangled.
Bytes received (example):
`[12, 98, 20, 0, 12, 98, 20, 0, 117, 101, 117, 101, 95, 100, 101, 112, 116, 104, 34, 58, 48, 44, 34, 108, 101, 97, 100, 101, 114, 98, 111, 97, 114, 100, 95, 113, 117, 101, 117, 101, 95, 100, 101, 112, 116, 104, 34, 58, 50, 57, 50, 44, 34, 119, 101, 98, 104, 111, 111, 107, 95, 113, 117, 101, 117, 101, 95, 100, 101, 112, 116, 104, 34, 58, 48, 125]`
As you can see, the first 8 bytes are even <32, which is in UTF8 special chars, and thus the "json" is garbage.

On another json, which is quite large, I get a big chunk of garbage; I don't have the raw bytes here, but text should suffice...
`JSON Received: Ð½\u0015\u0000Ð½\u0015\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u001cc\u0014\u0000\u0010\u0000\u0000\u0000764746\",\"player\"[...]`

I am compiling with profile
```toml
[profile.release]
opt-level = "s"
```

**Comment by jakubadamw** [comment]
@zebp seeing a very similar issue to this one after upgrading our workers to 0.0.14.
![image](https://user-images.githubusercontent.com/14150873/225035157-f4922ef4-8e1d-4db2-8262-61d4742ec459.png)

**Comment by jakubadamw** [comment]
@zebp ok, I think the fix from https://github.com/cloudflare/workers-rs/pull/115/files essentially got rolled back during some of the recent refactors. Looking into a fix.

**Comment by jakubadamw** [comment]
PR with the fix brought back again: https://github.com/cloudflare/workers-rs/pull/291.
