### ISSUE TITLE
Why not use `http`'s StatusCode to represent status code?

### ISSUE THREAD

**Issue by equt** [cloudflare/workers-rs#86]
It seems weird for me that functions like `Response::error` [still takes a `u16` as the response status code, and `impl Into<String>` as the response description](https://github.com/cloudflare/workers-rs/blob/b48e7ad72f8eed638fb52931e4f4bfeb4838dc0e/worker/src/response.rs?_pjax=%23js-repo-pjax-container%3Afirst-of-type%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%3Afirst-of-type%2C%20%5Bdata-pjax-container%5D%3Afirst-of-type#L106), since the crate `http` has already been a dep. So I'm expecting to have sigs like

```rust
pub fn error(code: http::StatusCode) -> Result<Self>;
pub fn status_code(&self) -> http::StatusCode;
```

Wrapping around `http::StatusCode` to have custom types like `ErrorStatusCode` will also allow us us to lift the following error to type-level & reduce runtime cost (well, maybe just a little). And I believe this is an error that should not be thrown in runtime.

```rust
if !(400..=599).contains(&status) {
    return Err(Error::Internal(
        "error status codes must be in the 400-599 range! see https://developer.mozilla.org/en-US/docs/Web/HTTP/Status for more".into(),
    ));
}
```

**Comment by nilslice** [comment]
Hi @equt - 

I'd definitely accept a PR if you wanted to take a pass at your suggestion. There are other "ecosystem compatibility" considerations we are tracking and thinking through as well, and tend to agree this is a good idea. These were mainly omitted at first for simplicity, and then further for consistency, but it's a great time to re-visit & make updates. 

As far as removing the runtime error, it wouldn't prevent anything since the underlying Workers runtime will also throw here under the same conditions. This is mostly an attempt to give you a chance at changing the `Response` before it is returned, if you happen to handle this error.

**Comment by equt** [comment]
A major version bump should be expected since it changes the exposed API drastically. I'll take a try in these few days.

> it wouldn't prevent anything since the underlying Workers runtime will also throw here under the same conditions

I'm not sure how the underlying runtime could affect this, by rewriting the `Response::error` to the following code

```rust
// Derive Into<http::StatusCode>
pub enum ErrorStatusCode {
    BadRequest,
    // ...
}

/// A helper method to send an error message to a client. Will return `Err` if the status code
/// provided is outside the valid HTTP error range of 400-599.
pub fn error(code: ErrorStatusCode) -> Result<Self> {
    Ok(Self {
         body: ResponseBody::Body(/* message from StatusCode */),
        headers: Headers::new(),
        status_code: /* status from StatusCode */,
    })
}
```

Users could always pass a valid error status code in. Or do you mean the underlying code like glue code generated by the `worker-build` will do some validations?

**Comment by jyn514** [comment]
Yeah, this is a special case of https://github.com/cloudflare/workers-rs/issues/13.

**Comment by equt** [comment]
Yep, forward to that issue.
